project:
  name: simple-management-system
  version: 1.0.0
  env: development

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/liuy307?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin

mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.liuyong.simplems.dao
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger:
  host:
  title: ${project.name}接口文档
  description: ${project.name}接口文档
  enabled: true
  #禁用swagger时的重定向地址
  redirect-uri: /


