project:
  name: simple-management-system
  version: 1.0.0
  env: development

server:
  port: 8080

#  datasource:
#    dynamic:com.mysql.cj.jdbc.Driver
#      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
#      p6spy: true
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/liuy307?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin

#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/liuy307?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: admin

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0

mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.liuyong.simplems.dao
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger:
  host:
  title: ${project.name}接口文档
  description: ${project.name}接口文档
  enabled: true
  #禁用swagger时的重定向地址
  redirect-uri: /

logging:
  file:
    name: ms.log
    path: D:\\
#  level:
#    root: DEBUG



