server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/liuy307?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.liuyong.simplems.dao


